# Generated by Django 5.1.2 on 2024-11-01 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance_system', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
