# Generated by Django 5.1.2 on 2024-11-16 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance_system', '0003_remove_attendance_is_approved_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='status',
            field=models.CharField(choices=[('unupdated', '未更新'), ('pending', '申請中'), ('approved', '承認済み'), ('rejected', '再提出')], default='unupdated', max_length=20),
        ),
    ]
