# Generated by Django 5.1.2 on 2024-11-16 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance_system', '0004_alter_attendance_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='is_approved',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
    ]
